### ISSUE TITLE
Want to easily get through to the service "echobot"

### ISSUE THREAD

**Issue by torvn77** [loadletter/pydaisy#1]
Since I can not find ID of service "echobot", offer to do one of two things
OR)Add the functionality of the service "echobot" in service "groupbot".
OR) to Make the service "grupboot" special command adds the service "echobot" in the contact list.

**Comment by loadletter** [comment]
Sorry, I didn't understand much of what you've written, but I haven't updated this in a while so it probably doesn't work with newer versions of pytox, as for groupbot I think it should still be this one https://wiki.tox.chat/users/groupbot

**Comment by torvn77** [comment]
1)There is a service "echobot"
2)This service "echobot" is used to test a communication channel by the method of the return echo.
2)Find ID of this service in dedicated Tox wiki is extremely difficult,
and when I looked for it last time I just couldn't find it.
3)I suggest to make the service "groupbot" special command to add them to my contact list, in order I no longer had to look for his ID.

**Comment by loadletter** [comment]
This is not the groupbot, I believe the bot used as groupbot is this one https://github.com/JFreegman/ToxBot but it's probably better to ask on the IRC channels.
Echobot's ID is on this page https://toxme.io/u/echobot

**Comment by torvn77** [comment]
Thank you
